// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sahadLearn.API.Data;

#nullable disable

namespace sahadLearn.API.Migrations
{
    [DbContext(typeof(sahadLearnDbContext))]
    [Migration("20261006093054_Seeding data for Difficulties and Regions")]
    partial class SeedingdataforDifficultiesandRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sahadLearn.API.models.domains.Difficulty", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            id = new Guid("54466f17-02af-48e7-8ed3-5a4a8bfacf6f"),
                            name = "Easy"
                        },
                        new
                        {
                            id = new Guid("ea294873-7a8c-4c0f-bfae-5d6a0a3f3a31"),
                            name = "Medium"
                        },
                        new
                        {
                            id = new Guid("f808ddcd-b5e5-4d80-b732-1ca523e48434"),
                            name = "Hard"
                        });
                });

            modelBuilder.Entity("sahadLearn.API.models.domains.Region", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            id = new Guid("f7248fc3-2585-4efb-8d1d-1c555f4087f6"),
                            Code = "AKL",
                            RegionImage = "https://images.pexels.com/photos/5169056/pexels-photo-5169056.jpeg",
                            name = "Auckland"
                        },
                        new
                        {
                            id = new Guid("6884f7d7-ad1f-4101-8df3-7a6a0b2d9a14"),
                            Code = "NTL",
                            name = "Northland"
                        },
                        new
                        {
                            id = new Guid("14ceba71-4b51-4777-9b17-46602cf66153"),
                            Code = "BOP",
                            name = "Bay Of Plenty"
                        },
                        new
                        {
                            id = new Guid("cfa06ed2-bf65-4b65-93ed-c9d286ddb0de"),
                            Code = "WGN",
                            RegionImage = "https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpeg",
                            name = "Wellington"
                        },
                        new
                        {
                            id = new Guid("906cb139-415a-4bbb-a174-1a1faf9fb1f6"),
                            Code = "NSN",
                            RegionImage = "https://images.pexels.com/photos/13918194/pexels-photo-13918194.jpeg",
                            name = "Nelson"
                        },
                        new
                        {
                            id = new Guid("f077a22e-4248-4bf6-b564-c7cf4e250263"),
                            Code = "STL",
                            name = "Southland"
                        });
                });

            modelBuilder.Entity("sahadLearn.API.models.domains.Walk", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Defficaltyid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LegthInKm")
                        .HasColumnType("float");

                    b.Property<Guid>("RegionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("difficaltyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Defficaltyid");

                    b.HasIndex("RegionID");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("sahadLearn.API.models.domains.Walk", b =>
                {
                    b.HasOne("sahadLearn.API.models.domains.Difficulty", "Defficalty")
                        .WithMany()
                        .HasForeignKey("Defficaltyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sahadLearn.API.models.domains.Region", "Rigion")
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defficalty");

                    b.Navigation("Rigion");
                });
#pragma warning restore 612, 618
        }
    }
}
